name: cloud-for-climate-dev
channels:
  - conda-forge
  - nodefaults
  - pyviz
dependencies:
  - python>=3.8
  - xarray
  - kerchunk
  - fsspec
  - netcdf4
  - jupyterlab
  - pip
  - h5py
  - zarr
  - bokeh
  - matplotlib
  - intake-xarray
  - hvplot
  - pip:
    - s3fs
    - nc-time-axis
