title: Cloud for Climate
author: Silverlinings Project Team
logo: images/silverlining-logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
html:
  comments:
    hypothesis: true
repository:
  url: https://github.com/mgrover1/cloud-for-climate  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url: "https://jupyterhub.hpc.ucar.edu"